---
title: "Reporte Epidemiológico SIVILE 2024"
author: Instituto Nacional de Epidemiología
format: 
    dashboard:
        orientation: columns
        vertical_layout: fill
        theme: custom.scss
server: shiny
---

```{r}
#| id: Cargar paquetes
#| context: setup
pacman::p_load(
  # Quarto
  quarto,
  # Interactividad
  shiny,
  # Mapas
  sf,
  leaflet,
  geoAr,
  rnaturalearth,
  mapview,
  # Gráficos
  cols4all,
  apyramid,
  patchwork,
  cowplot,
  labelled,
  # Tablas
  DT,
  # Manejo de datos
  rio,
  janitor,
  scales,
  tidyverse
)

### La app se renderiza con:
# quarto_publish_app(server = "shinyapps.io", account = "datos-ine")
```

```{r}
#| id: Cargar datos SIVILE
#| context: setup
##  Cargar resumen dataset
res <- import("clean/resumen.csv")

## Cargar datos SIVILE
datos <- import("clean/clean_SIVILE_2024.rds", trust = TRUE)
```

```{r}
#| id: Capas GIS
#| context: setup
## URL mapas base ----
argenmap <- "https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{-y}.png
"

argenmap_hyb <- "https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/mapabase_hibrido@EPSG%3A3857@png/{z}/{x}/{-y}.png
"

## Cargar shapefile provincias ----
get_shp_arg <- possibly(
  ~ get_geo("ARGENTINA", level = "provincia"),
  otherwise = ne_states(country = "Argentina")
)

shp_arg <- get_shp_arg() |>
  add_geo_codes() |>
  mutate(name_iso = if_else(codprov == "01", "CABA", name_iso)) |>
  st_point_on_surface()
```

```{r}
#| id: Temas personalizados
#| context: server
# Tema personalizado tablas
tab_format <- function(x) {
  library(DT)
  x |>

    datatable(
      rownames = FALSE,
      colnames = c(var_label(x) |> as.character()),
      #filter = "top",
      escape = FALSE,
      options = list(
        searching = TRUE,
        info = FALSE,
        paging = FALSE,
        autoWidth = FALSE,
        dom = 'Bftlp'
      )
    ) |>

    formatPercentage(columns = "pct", digits = 2)
}


# Tema personalizado para gráficos
tema_sivile <- function() {
  list(
    scale_color_discrete_c4a_cat(palette = input$pal4),
    theme_minimal(),
    theme(
      legend.position = input$legend,
      title = element_text(face = "bold"),
      axis.text.x = element_text(angle = 60)
    )
  )
}

## Crear capa base Argentina
mapa_base <- function(x) {
  x |>
    # Capa base Argentina
    leaflet(options = leafletOptions(minZoom = 3, maxZoom = 8)) |>
    addTiles(
      urlTemplate = input$base1,
      attribution = "<a href='https://www.ign.gob.ar/' target='_blank'>Instituto Geográfico Nacional (IGN)</a>"
    )
}
```

# UCL
## Valuebox {width="25%"}

```{r}
#| content: valuebox
#| title: UCL SIVILE activas
#| icon: hospital
#| color: primary
list(value = res$n_ucl)
```

```{r}
#| content: valuebox
#| title: Registros totales
#| icon: file-text
list(value = res$n)
```

```{r}
#| content: valuebox
#| title: Registros válidos (*)
#| icon: file-text
#| color: warning
list(value = nrow(datos))
```

<div style="font-size:0.5rem;">
(*) Datos completos para las variables de carga obligatoria: código establecimiento, sexo, edad, fecha de lesión, mecanismo, intencionalidad y egreso.
</div>

## Mapa {width="75%"}

```{r}
#| id: Mapa 1
#| context: server
# Crear shapefile para el mapa
datos_mapa <- shp_arg |>
  select(name_iso) |>
  inner_join(
    datos |>
      count(prov_ucl, id_prov_ucl) |>
      mutate(pct = n / sum(n, na.rm = TRUE)),
    by = join_by(name_iso == prov_ucl)
  ) |>
  arrange(name_iso)

## Renderizar mapa
output$mapa1 <- renderLeaflet({
  req(mapa_base, datos_mapa)

  # Crear paletas colorblind-friendly
  pal <- colorNumeric(
    palette = c4a(palette = input$pal1),
    domain = c(0, max(datos_mapa$n, na.rm = TRUE))
  )

  # Crear mapa interactivo
  m1 <- datos_mapa |>
    mapa_base() |>

    # Capa casos x UCL x provincia
    addCircleMarkers(
      radius = rescale(sqrt(datos_mapa$n), to = c(5, 15)),
      fillOpacity = 0.75,
      fillColor = pal(datos_mapa$n),
      stroke = TRUE,
      color = "grey",
      weight = 2,
      clusterOptions = markerClusterOptions(
        maxClusterRadius = 10
      ),
      popup = ~ paste0(
        "<b>Provincia: </b> ",
        name_iso,
        "<br>",
        "<b>UCL: </b>",
        id_prov_ucl,
        "<br>",
        "<b>Casos: </b>",
        n,
        "<b> Porcentaje: </b>",
        percent(pct, accuracy = .1)
      )
    ) |>

    # Añadir leyenda
    addLegend(
      title = "Casos por UCL",
      pal = pal,
      values = datos_mapa$n,
      position = "bottomright"
    )

  # Mostrar mapa
  m1
})


## Guardar datos del mapa como CSV
output$down_csv1 <- downloadHandler(
  filename = function() {
    paste0("datos_casos_UCL_2024", ".csv")
  },
  content = function(file) {
    datos_mapa |>
      st_drop_geometry() |>
      export(file = file, encoding = "UTF-8")
  }
)

## Guardar datos del mapa como XLSX
output$down_excel1 <- downloadHandler(
  filename = function() {
    paste0("datos_casos_UCL_2024", ".xlsx")
  },
  content = function(file) {
    datos_mapa |>
      st_drop_geometry() |>
      export(file = file, encoding = "UTF-8")
  }
)
```

```{r}
#| id: Toolbar mapa 1
#| content: card-toolbar
## Selector de colores
selectInput(
  inputId = "pal1",
  label = "Paleta",
  choices = c(
    "Managua" = "scico.managua",
    "Icefire" = "icefire",
    "Tokyo" = "-scico.tokyo",
    "Viridis" = "-viridis"
  ),
  selected = "-viridis"
)

## Mapa base
selectInput(
  inputId = "base1",
  label = "Capa base",
  choices = c(
    "Argenmap (híbrido)" = argenmap_hyb,
    "Argenmap (color)" = argenmap
  )
)

## Descargar datos
tags$p("Descargar datos:")

# CSV
downloadButton(
  outputId = "down_csv1",
  label = NULL,
  icon = icon("file-csv"),
  class = "btn-download"
)

# Excel
downloadButton(
  outputId = "down_excel1",
  label = NULL,
  icon = icon("file-excel"),
  class = "btn-download"
)
```

```{r}
#| id: Mostrar mapa 1
leafletOutput("mapa1")
```

# Provincia
## Mapa {width="50%"}
```{r}
#| id: Mapa 2
#| context: server
# Crear mapa
output$mapa2 <- renderLeaflet({
  req(input$prov, input$estr1, input$pal2, input$base1)

  # Definir variables
  prov <- input$prov
  estrato <- input$estr1

  # Crear datos para el mapa
  if (prov == "id_prov_ucl") {
    datos_mapa <- datos |>
      count(prov_ucl, id_prov_ucl, !!sym(estrato)) |>
      pivot_wider(
        names_from = !!sym(estrato),
        values_from = n
      ) |>
      mutate(Total = rowSums(across(where(is.numeric)))) |>
      rename(name_iso = prov_ucl)
  } else {
    datos_mapa <- datos |>
      count(!!sym(prov), !!sym(estrato)) |>
      pivot_wider(
        names_from = !!sym(estrato),
        values_from = n
      ) |>
      mutate(Total = rowSums(across(where(is.numeric)))) |>
      rename(name_iso = !!sym(prov))
  }

  # Añadir geometrías
  datos_mapa <- shp_arg |> inner_join(datos_mapa)

  # Crear paleta de colores colorblind-friendly
  pal <- colorNumeric(
    palette = c4a(palette = input$pal2),
    domain = c(0, max(datos_mapa$Total, na.rm = TRUE))
  )

  # Niveles estratificación
  cat <- names(datos_mapa |> st_drop_geometry() |> select(where(is.numeric)))

  # Crear mapa base
  m2 <- datos_mapa |>
    # Capa base Argentina
    mapa_base() |>
    # Leyenda
    addLegend(title = "Frecuencia", pal = pal, values = datos_mapa$Total) |>
    # Control de capas
    addLayersControl(
      overlayGroups = cat,
      options = layersControlOptions(collapsed = TRUE)
    ) |>
    hideGroup(cat[cat != "Total"])

  # Círculos reactivos
  for (x in cat) {
    m2 <- m2 |>
      addCircleMarkers(
        data = datos_mapa,
        radius = rescale(sqrt(datos_mapa[[x]]), to = c(5, 15)),
        fillColor = pal(datos_mapa[[x]]),
        fillOpacity = 0.75,
        stroke = TRUE,
        color = "grey",
        weight = 2,
        clusterOptions = markerClusterOptions(maxClusterRadius = 10),
        popup = ~ paste0(
          "<b>Provincia: </b>",
          name_iso,
          "<br><b>Casos: </b>",
          get(x)
        ),
        group = x
      )
  }
  # Mostrar
  m2
})
```

```{r}
#| id: Toolbar mapa 2
#| content: card-toolbar
## Selector de variable provincia
selectInput(
  inputId = "prov",
  label = "Mostrar datos por",
  choices = names(datos)[str_detect(names(datos), "prov")] |>
    set_names(var_label(datos)[str_detect(names(datos), "prov")])
)

## Selector de estratos
selectInput(
  inputId = "estr1",
  label = "Frecuencias por",
  choices = c(
    "Sexo" = "sexo",
    "Edad" = "grupo_edad",
    "Intencionalidad" = "intencionalidad"
  )
)

## Selector de colores
selectInput(
  inputId = "pal2",
  label = "Paleta de colores",
  choices = c(
    "Managua" = "scico.managua",
    "Icefire" = "icefire",
    "Tokyo" = "-scico.tokyo",
    "Viridis" = "-viridis"
  ),
  selected = "-viridis"
)

## Mapa base
selectInput(
  inputId = "base1",
  label = "Mapa base",
  choices = c(
    "Argenmap (híbrido)" = argenmap_hyb,
    "Argenmap (color)" = argenmap
  )
)
```

```{r}
#| id: Mostrar mapa 2
leafletOutput("mapa2")
```

## Tabla x provincia
```{r}
#| id: Tabla 1
#| context: server
# Tabla reactiva
tab1_data <- reactive({
  # Dataset para la tabla
  datos_tab <- datos |>
    select(
      contains("prov_"),
      sexo,
      grupo_edad,
      intencionalidad,
      mecanismo,
      egreso
    )

  # Variables
  vars <- intersect(input$estr2, names(datos_tab))
  provincia <- input$prov

  # Si no se selecciona estrato mostrar frecuencia por provincia
  if (length(vars) == 0) {
    datos_tab |>
      count(!!sym(provincia)) |>
      mutate(pct = n / sum(n, na.rm = TRUE)) |>
      set_variable_labels(
        .labels = list(
          n = "Frecuencia",
          pct = "Porcentaje"
        )
      )
  } else {
    datos_tab |>
      count(!!sym(provincia), across(any_of(vars))) |>
      mutate(pct = n / sum(n, na.rm = TRUE), .by = provincia) |>
      set_variable_labels(
        .labels = list(
          n = "Frecuencia",
          pct = "Porcentaje"
        )
      )
  }
})

## Renderizar tabla DT
output$tab1 <- renderDT({
  # source("tab_format.R")

  tab1_data() |>
    tab_format()
})

## Descargar como CSV
output$down_csv2 <- downloadHandler(
  filename = function() paste0("tabla_casos_", 2024, ".csv"),
  content = function(file) export(tab1_data(), file)
)

## Descargar como Excel
output$down_excel2 <- downloadHandler(
  filename = function() paste0("tabla_casos_", 2024, ".xlsx"),
  content = function(file) export(tab1_data(), file)
)
```

```{r}
#| id: Toolbar tabla 1
#| content: card-toolbar
## Selector de estratos
selectInput(
  inputId = "estr2",
  label = "Estratificar por",
  multiple = TRUE,
  choices = c(
    "Sexo" = "sexo",
    "Edad" = "grupo_edad",
    "Intencionalidad" = "intencionalidad",
    "Mecanismo" = "mecanismo",
    "Egreso" = "egreso"
  )
)

## Descargar datos
tags$p("Descargar tabla:")

# CSV
downloadButton(
  outputId = "down_csv2",
  label = NULL,
  icon = icon("file-csv"),
  class = "btn-download"
)

# Excel
downloadButton(
  outputId = "down_excel2",
  label = NULL,
  icon = icon("file-excel"),
  class = "btn-download"
)
```

```{r}
#| id: Mostrar tabla 1
DTOutput("tab1")
```

# Gráficos

```{r}
#| id: Dataset para el gráfico 1
#| context: setup
# Crear dataset para el gráfico
datos_g1 <- datos |>
  select(
    id_prov_ucl,
    grupo_edad,
    sexo,
    nivel_instruccion,
    sit_laboral,
    lugar_lesion,
    mecanismo,
    intencionalidad,
    egreso,
    tipo_lesion
  )
```

```{r}
#| id: Gráfico 1
#| context: server
## Gráfico pirámides reactivo
g1 <- reactive({
  req(datos_g1, input$sel1, input$estr3, input$estr4, input$pal3)

  # Definir variables
  x <- input$estr3
  y <- input$estr4

  # Filtrar por UCL
  if (input$sel1 != "Total país") {
    datos_g1 <- datos_g1 |>
      filter(id_prov_ucl == input$sel1) |>
      droplevels()
  }

  # Paleta colorblind-friendly
  pal <- c4a(input$pal3, n = nlevels(datos[[y]]))

  # Generar gráfico
  datos_g1 |>
    age_pyramid(
      age_group = any_of(x),
      split_by = any_of(y),
      proportional = input$prop,
      pal = pal
    ) +
    # Títulos
    labs(
      x = var_label(datos[[x]]),
      y = "Frecuencia",
      fill = var_label(datos[[y]]),
      title = paste0(
        "Lesiones por causas externas según ",
        var_label(datos[[x]]),
        " y ",
        var_label(datos[[y]]),
        ", SIVILE (2024)"
      )
    ) +
    tema_sivile()
})


## Renderizar gráfico
output$plot1 <- renderPlot({
  g1()
})


## Guardar gráfico como PNG
output$down_png1 <- downloadHandler(
  filename = function() {
    paste0("lesiones_", input$estr3, "_", input$estr4, "_", 2024, ".png")
  },
  content = function(file) {
    ggsave(
      filename = file,
      plot = g1(),
      width = 8,
      height = 6,
      dpi = 300
    )
  }
)

## Guardar gráfico como PDF
output$down_pdf1 <- downloadHandler(
  filename = function() {
    paste0("lesiones_", input$estr3, "_", input$estr4, "_", 2024, ".pdf")
  },
  content = function(file) {
    ggsave(
      filename = file,
      plot = g1(),
      width = 8,
      height = 6,
      dpi = 300
    )
  }
)
```


```{r}
#| id: Toolbar gráfico de pirámides
#| content: card-toolbar
## Filtro
selectInput(
  inputId = "sel1",
  label = "Filtrar por",
  choices = c(
    "Total país",
    datos_g1 |>
      filter(n() >= 200, .by = id_prov_ucl) |>
      distinct(id_prov_ucl)
  )
)

## Variable X
selectInput(
  inputId = "estr3",
  label = "Categoría",
  choices = names(datos_g1)[c(2:3)] |>
    set_names(var_label(datos_g1)[c(2:3)])
)

# Estrato
selectInput(
  inputId = "estr4",
  label = "Estrato",
  choices = names(datos_g1)[-c(1:2)] |>
    set_names(var_label(datos_g1)[-c(1:2)])
)

## Selector de colores
selectInput(
  inputId = "pal3",
  label = "Paleta de colores",
  choices = c(
    "Managua" = "scico.managua",
    "Icefire" = "icefire",
    "Tokyo" = "-scico.tokyo",
    "Viridis" = "-viridis"
  ),
  selected = "-viridis"
)

## Mostrar como proporción
selectInput(
  inputId = "prop",
  label = "Mostrar",
  choices = c(
    "Porcentaje" = TRUE,
    "Observaciones" = FALSE
  )
)

## Posición leyenda
selectInput(
  inputId = "legend",
  label = "Leyenda",
  choices = c(
    "Abajo" = "bottom",
    "Arriba" = "top",
    "Ocultar" = "none"
  )
)

## Descargar datos
tags$p("Descargar como:")

# PNG
downloadButton(
  outputId = "down_png1",
  label = NULL,
  icon = icon("file-image"),
  class = "btn-download"
)

# PDF
downloadButton(
  outputId = "down_pdf1",
  label = NULL,
  icon = icon("file-pdf"),
  class = "btn-download"
)
```

```{r}
#| id: Mostrar gráfico
plotOutput("plot1")
```

# Transporte

```{r}
#| id: Gráficos lesiones x transporte
#| context: setup
# Crear dataset transporte
datos_tr <- datos |>
  # Filtrar datos
  filter(mecanismo == "Transporte") |>

  # Cambiar a fecha
  mutate(mes_anio_lesion = my(mes_anio_lesion)) |>

  # Seleccionar columnas relevantes
  select(
    id_prov_ucl,
    mes_anio_lesion,
    prov_lesion,
    sexo,
    grupo_edad,
    lugar_lesion,
    evento_multiple,
    cond_lesionado:asiento_ninos,
    evid_alcohol:egreso
  )
```

## Serie temporal

```{r}
#| id: Gráfico 2
#| context: server
# Crear gráfico
output$g2 <- renderPlot({
  req(datos_tr, input$sel2, input$estr5, input$pal4)

  estr <- input$estr5

  # Datos para el gráfico
  if (input$sel2 != "Total país") {
    datos_plot <- datos_tr |>
      filter(id_prov_ucl == input$sel2) |>
      count(across(c(mes_anio_lesion, any_of(estr)))) |>
      drop_na()
  } else {
    datos_plot <- datos_tr |>
      droplevels() |>
      count(across(c(mes_anio_lesion, any_of(estr)))) |>
      drop_na()
  }

  # Serie temporal
  g2 <- datos_plot |>
    ggplot(aes(
      x = mes_anio_lesion,
      y = n,
      group = .data[[estr]],
      color = .data[[estr]]
    )) +

    # Geomas
    geom_point() +
    geom_line() +

    # Formato eje X
    scale_x_date(labels = label_date_short(), date_breaks = "2 months") +

    # Títulos
    labs(
      x = NULL,
      color = var_label(datos_tr[[estr]]),
      title = paste0(
        "Frecuencia mensual de lesiones por ",
        str_to_lower(var_label(datos_tr[[estr]])),
        ", SIVILE (2024)"
      )
    ) +

    # Tema
    tema_sivile()

  # Mostrar gráfico
  g2
})
```

```{r}
#| id: Toolbar Gráfico 2
#| content: card-toolbar
## Filtro
selectInput(
  inputId = "sel2",
  label = "Filtrar por",
  choices = c(
    "Total país",
    datos |>
      filter(n() >= 200, .by = id_prov_ucl) |>
      distinct(id_prov_ucl)
  )
)

# Seleccionar variable Y
selectInput(
  inputId = "estr5",
  label = "Estratificar por",
  choices = names(datos_tr)[-c(1:2)] |>
    set_names(var_label(datos_tr)[-c(1:2)])
)

## Selector de colores
selectInput(
  inputId = "pal4",
  label = "Paleta de colores",
  choices = c(
    "Managua" = "scico.managua",
    "Icefire" = "icefire",
    "Tokyo" = "-scico.tokyo",
    "Viridis" = "-viridis"
  ),
  selected = "-viridis"
)

## Posición leyenda
selectInput(
  inputId = "legend",
  label = "Leyenda",
  choices = c(
    "Abajo" = "bottom",
    "Arriba" = "top",
    "Ocultar" = "none"
  )
)
```

```{r}
#| id: Mostrar Gráfico 2
plotOutput("g2")
```

## Col2